### ISSUE TITLE
开发环境

### ISSUE THREAD

**Issue by sunweiyige** [Orangejlu/Orange#1]
eclipse 显示有错 但是可以运行 就是选课的页面首字母大写 是你故意的吗？

**Comment by sunweiyige** [comment]
学生选课404 帮忙解决一下 谢谢

**Comment by youthlin** [comment]
您好，感谢关注。这个项目原本是在IntelliJ IDEA下进行的，你用IDEA就好了。
（这只是一个课程设计的作业而已，使用的也是很简单的JSP+Servlet，做得很不完善，并没有什么软用）
